# ---
# title: User-wide Configuration for perltidy
# ---

# ---

# Default indentation
-i=4

# Whether to add extra indentation for comments
-ci=0

# No blank lines inserted before blocks
-npb

# No insertion of unnecessary blank lines in general
-bbl

# Maximum line length
-l=0

# Whether to reposition '(' in function calls
-pt=0

# No insertion of spaces around list elements: keeps my($a,$b,@c)=@_;
-lcl

# No insertion of extra spaces in subroutine/method call arguments
-lps

# No spaces inside parentheses for function calls
-lpm

# No indentation of comments
-ptc

# No spaces before comments
-ns

# Whether to insert extra spacing around operators
-op=0

# No adding of blank lines around semicolons
-sls

# Not adding of spaces around block operators { ... }
-sbp
