# flake8 global config file

# Recent versions of flake8 do not allow directly a global config file, compare with:
# [[https://stackoverflow.com/questions/28436382][flake8 not picking up config file]]

[flake8]

# Print the total number of errors
count = True

# Report all errors, even if it is on the same line as a # NOQA comment
disable_noqa = False

# Enable PyFlakes syntax checking of doctests in docstrings
doctests = True

# Specify a list of glob patterns to add to the list of excluded ones
extend-exclude =
tests/*,

# Specify a list of codes to add to the list of ignored ones
extend-ignore =
# # E251: Unexpected spaces around keyword / parameter equals
# E251,
# # W503: Line break before binary operator
# W503,
# # F812: list comprehension redefines ...
# F812,
# # H101: Use TODO(NAME)
# H101,
# # H202: assertRaises Exception too broad
# H202,
# # H233: Python 3.x incompatible use of print operator
# H233,
# # H301: one import per line
# H301,
# # H306: imports not in alphabetical order (time, os)
# H306,
# # H401: docstring should not start with a space
# H401,
# # H403: multi line docstrings should end on a new line
# H403,
# # H404: multi line docstring should start without a leading new line
# H404,
# # H405: multi line docstring summary not separated with an empty line
# H405,
# # H501: Do not use self.__dict__ for string formatting
# H501,

# Set the number of spaces used for indentation
indent-size = 4

# Specify the number of subprocesses that Flake8 will use to run checks in parallel.
jobs = auto

# Set the maximum allowed McCabe complexity value for a block of code
max-complexity = 10

# Set the maximum length that any line (with some exceptions) may be
max-line-length = 70

# Print the source code generating the error/warning in question
show_source = True

# Count the number of occurrences of each error/warning code and print a report
statistics = True
